# Assignment-3
## UCS420 "Cognitive Computing"
### Pandas

In [1]:
#Assignment 1: WAP to create a dataset as given in the table.
import pandas as pd

data = {
    "Tid": [1,2,3,4,5,6,7,8,9,10],
    "Refund": ["Yes","No","No","Yes","No","No","Yes","No","No","No"],
    "Marital Status": ["Single","Married","Single","Married","Divorced","Married","Divorced","Single","Married","Single"],
    "Taxable Income": ["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat": ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}

df = pd.DataFrame(data)
df.set_index("Tid", inplace=True)
df

    Refund Marital Status Taxable Income Cheat
Tid
1      Yes         Single           125K    No
2       No        Married           100K    No
3       No         Single            70K    No
4      Yes        Married           120K    No
5       No       Divorced            95K   Yes
6       No        Married            60K    No
7      Yes       Divorced           220K    No
8       No         Single            85K   Yes
9       No        Married            75K    No
10      No         Single            90K   Yes

In [2]:
#Assignment 2: WAP to locate row 0, 4, 7 and 8 using DataFrame.
df.iloc[[0,4,7,8]]

    Refund Marital Status Taxable Income Cheat
Tid
1      Yes         Single           125K    No
5       No       Divorced            95K   Yes
8       No         Single            85K   Yes
9       No        Married            75K    No

In [3]:
#Assignment 3.1: Select row from index 3 to 7.
df.iloc[3:8]

    Refund Marital Status Taxable Income Cheat
Tid
4      Yes        Married           120K    No
5       No       Divorced            95K   Yes
6       No        Married            60K    No
7      Yes       Divorced           220K    No
8       No         Single            85K   Yes

In [4]:
#Assignment 3.2: Select row from index 4 to 8, and column 2 to 4.
df.iloc[4:9, 2:4]

    Taxable Income Cheat
Tid
5              95K   Yes
6              60K    No
7             220K    No
8              85K   Yes
9              75K    No

In [5]:
#Assignment 3.3: Select all rows with column index 1 to 3 (include index 3 during selection).
df.iloc[:, 1:4]

    Marital Status Taxable Income Cheat
Tid
1           Single           125K    No
2          Married           100K    No
3           Single            70K    No
4          Married           120K    No
5         Divorced            95K   Yes
6          Married            60K    No
7         Divorced           220K    No
8           Single            85K   Yes
9          Married            75K    No
10          Single            90K   Yes

In [6]:
#Assignment 4: WAP to read a csv file and display its first five rows.
#Note: Iris dataset downloaded from https://www.kaggle.com/datasets/uciml/iris
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
iris_df = iris.frame
iris_df["species"] = iris_df["target"].map(dict(enumerate(iris.target_names)))
iris_df.drop(columns=["target"], inplace=True)
iris_df.to_csv("Iris.csv", index_label="Id")

iris_data = pd.read_csv("Iris.csv")
iris_data.head()

,Id,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,0,5.1,3.5,1.4,0.2,setosa
1,1,4.9,3.0,1.4,0.2,setosa
2,2,4.7,3.2,1.3,0.2,setosa
3,3,4.6,3.1,1.5,0.2,setosa
4,4,5.0,3.6,1.4,0.2,setosa

In [7]:
#Assignment 5: WAP to delete row 4, and delete column 3 from the csv file (uploaded in Q.4). Display the result.
iris_modified = iris_data.drop(index=4)
iris_modified = iris_modified.drop(iris_modified.columns[3], axis=1)
iris_modified.head()

   Id  sepal length (cm)  sepal width (cm)  petal width (cm) species
0   0                5.1               3.5               0.2  setosa
1   1                4.9               3.0               0.2  setosa
2   2                4.7               3.2               0.2  setosa
3   3                4.6               3.1               0.2  setosa
5   5                5.4               3.9               0.4  setosa

### Q.6 Employees dataset

In [8]:
#Assignment 6: WAP to create a sample dataset (employees.csv) containing information about employees in a company.
emp_data = {
    "Employee_ID": [101,102,103,104,105],
    "Name": ["Alice","Bob","Charlie","Diana","Edward"],
    "Department": ["HR","IT","IT","Marketing","Sales"],
    "Age": [29,34,41,28,38],
    "Salary": [50000,70000,65000,55000,60000],
    "Years_of_Experience": [4,8,10,3,12],
    "Joining_Date": ["2020-03-15","2017-07-19","2013-06-01","2021-02-10","2010-11-25"],
    "Gender": ["Female","Male","Male","Female","Male"],
    "Bonus": [5000,7000,6000,4500,5000],
    "Rating": [4.5,4.0,3.8,4.7,3.5]
}

emp_df = pd.DataFrame(emp_data)
emp_df.to_csv("employees.csv", index=False)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [9]:
#a) Shape (number of rows and columns) of the DataFrame.
emp_df.shape

(5, 10)

In [10]:
#b) Summary of the DataFrame that includes the data types and non-null counts for each column.
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

In [11]:
#c) Generate descriptive statistics.
emp_df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [12]:
#d) Display the first 5 rows and last 3 rows of the dataset.
print("First 5 rows:")
display(emp_df.head())
print("Last 3 rows:")
display(emp_df.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [13]:
#e) i. The average salary of employees.
avg_salary = emp_df["Salary"].mean()
print("Average Salary:", avg_salary)

Average Salary: 60000.0

In [14]:
#e) ii. The total bonus paid to all employees.
total_bonus = emp_df["Bonus"].sum()
print("Total Bonus:", total_bonus)

Total Bonus: 27500

In [15]:
#e) iii. The youngest employee's age.
youngest_age = emp_df["Age"].min()
print("Youngest Employee's Age:", youngest_age)

Youngest Employee's Age: 28

In [16]:
#e) iv. The highest performance rating.
highest_rating = emp_df["Rating"].max()
print("Highest Performance Rating:", highest_rating)

Highest Performance Rating: 4.7

In [17]:
#f) Sort the DataFrame by the Salary column in descending order.
emp_df_sorted = emp_df.sort_values(by="Salary", ascending=False)
emp_df_sorted

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [18]:
#g) Add a new column that categorizes employees based on their performance rating.
def categorize(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

emp_df["Performance_Category"] = emp_df["Rating"].apply(categorize)
emp_df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [19]:
#h) Identify missing values in the DataFrame.
emp_df.isnull().sum()

Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

In [20]:
#i) Rename the Employee_ID column to ID.
emp_df.rename(columns={"Employee_ID":"ID"}, inplace=True)
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [21]:
#j) i. Employees with more than 5 years of experience.
emp_df[emp_df["Years_of_Experience"] > 5]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [22]:
#j) ii. Employees who belong to the IT department.
emp_df[emp_df["Department"] == "IT"]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [23]:
#k) Modify the dataset by adding a new column, Tax, which deducts 10% of the Salary.
emp_df["Tax"] = emp_df["Salary"] * 0.10
emp_df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance_Category,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0

In [24]:
#l) Save the modified DataFrame (with added columns) to a new CSV file.
emp_df.to_csv("employees_modified.csv", index=False)
print("File saved as employees_modified.csv")

File saved as employees_modified.csv